style:
  fontCacheDir: .cache/font/
  fonts:
    base:
      background: '#002b36' # base03
      foreground: '#ffffff'
      italic: false
      bold: false
      size: 14
      family:
        name: "Source Code Pro"
    # Text Colors
    base03:
      parent: base
      foreground: '#002b36'
    base02:
      parent: base
      foreground: '#073642'
    base01:
      parent: base
      foreground: '#586e75'
    base00:
      parent: base
      foreground: '#657b83'
    base0:
      parent: base
      foreground: '#839496'
    base1:
      parent: base
      foreground: '#93a1a1'
    base2:
      parent: base
      foreground: '#eee8d5'
    base3:
      parent: base
      foreground: '#fdf6e3'

    highlight:
      parent: base2
      background: '#073642' # base02
    highlight_low:
      parent: base2
    red:
      parent: base
      foreground: '#dc322f'
    green:
      parent: base
      foreground: '#859900'
    yellow:
      parent: base
      foreground: '#b58900'

    tac_primary:
      parent: base1
    tac_secondary:
      parent: base01
    tac_primary_selected:
      parent: tac_primary
      background: '#073642' # base02
    tac_secondary_selected:
      parent: tac_secondary
      background: '#073642' # base02

    dashboard_main:
      parent: base01
      size: 50
      family:
        name: "DejaVu Sans Light"
    dashboard_media:
      parent: dashboard_main
      size: 30
    dashboard_xkcd:
      parent: dashboard_main
      size: 16
      family:
        name: "DejaVu Sans"
icon:
  cacheDir: .cache/icon/
  icons:
    cpu: material-design-icons/hardware/1x_web/ic_memory_white_18dp.png
    battery_0: material-design-icons/device/1x_web/ic_battery_alert_white_18dp.png
    battery_20: material-design-icons/device/1x_web/ic_battery_20_white_18dp.png
    battery_30: material-design-icons/device/1x_web/ic_battery_30_white_18dp.png
    battery_50: material-design-icons/device/1x_web/ic_battery_50_white_18dp.png
    battery_60: material-design-icons/device/1x_web/ic_battery_60_white_18dp.png
    battery_80: material-design-icons/device/1x_web/ic_battery_80_white_18dp.png
    battery_90: material-design-icons/device/1x_web/ic_battery_90_white_18dp.png
    battery_100: material-design-icons/device/1x_web/ic_battery_full_white_18dp.png
    battery_20_charging: material-design-icons/device/1x_web/ic_battery_charging_20_white_18dp.png
    battery_30_charging: material-design-icons/device/1x_web/ic_battery_charging_30_white_18dp.png
    battery_50_charging: material-design-icons/device/1x_web/ic_battery_charging_50_white_18dp.png
    battery_60_charging: material-design-icons/device/1x_web/ic_battery_charging_60_white_18dp.png
    battery_80_charging: material-design-icons/device/1x_web/ic_battery_charging_80_white_18dp.png
    battery_90_charging: material-design-icons/device/1x_web/ic_battery_charging_90_white_18dp.png
    battery_100_charging: material-design-icons/device/1x_web/ic_battery_charging_full_white_18dp.png
    net_online: material-design-icons/action/1x_web/ic_settings_ethernet_white_18dp.png
    net_offline: material-design-icons/av/1x_web/ic_not_interested_white_18dp.png
    playing: material-design-icons/av/1x_web/ic_pause_white_18dp.png
    paused: material-design-icons/av/1x_web/ic_play_arrow_white_18dp.png

# Modules
dock:
  height: 20
  background: '#002b36'
  time: base0
  batteryTime: base0
  batteryTransition:
    low: red
    high: green
  chargingIcons:
    0.2: battery_20_charging
    0.3: battery_30_charging
    0.5: battery_50_charging
    0.6: battery_60_charging
    0.8: battery_80_charging
    0.9: battery_90_charging
    1.0: battery_100_charging
  dischargingIcons:
    0.0: battery_0
    0.2: battery_20
    0.3: battery_30
    0.5: battery_50
    0.6: battery_60
    0.8: battery_80
    0.9: battery_90
    1.0: battery_100
  cpuIcon: cpu
  cpuTransition:
    low: green
    high: red
  memoryTransition:
    low: green
    high: red
  swapTransition:
    low: green
    high: red
  clockFont: base0
  clockFormat: "uuuu-MM-dd HH:mm:ss"
  netUpFont: yellow
  netDownFont: red
  netIconFont: base0
  netIconOnline: net_online
  netIconOffline: net_offline
  activeFont: highlight
  activeElsewhereFont: highlight_low
  runningFont: base0
  emptyFont: base01
  windowTitleFont: base01
  progressColor: '#93a1a1'
  activeMonitorColor: '#59621b'
  mediaFont: base0
  mediaPlaying: playing
  mediaPaused: paused
tac:
  fontPrimary: tac_primary
  fontPrimarySelected: tac_primary_selected
  fontSecondary: tac_secondary
  fontSecondarySelected: tac_secondary_selected
  colorBackground: '#002b36'
  colorSelected: '#073642'
  width: 400
  rowHeight: 22
  padding: 3
dashboard:
  temperatureFont: dashboard_main
  mediaFont: dashboard_media
  pingFont: dashboard_media
  xkcdFont: dashboard_xkcd
  xkcdWhite: '#002b36'
  xkcdBlack: '#586e75'

  pingDestinations:
    ente: ente.hawo.stw.uni-erlangen.de
    yawk: yawk.at
    ps: ps.yawk.at
launcher:
  shortcuts:
    firefox:
      command: ["firefox"]
      jail: []
    thunderbird:
      command: ["thunderbird"]
      jail: []
    quasselclient:
      command: ["quasselclient"]
      jail:
      - "--profile=/etc/firejail/quassel.profile"
    subl:
      command: ["subl"]
    intellij:
      command: ["idea-ue-eap"]
      # can't do whitelist because we don't know the config dir because that changes every version :(
      jail: []
    ida:
      command: ["/opt/ida-demo/idaq"]
      jail:
      - "--whitelist=~/Development"
    genpw16:
      command: ["bash", "-c", "< /dev/urandom tr -dc A-Za-z0-9 | head -c${1:-16} | xclip -selection c"]
    genpw32:
      command: ["bash", "-c", "< /dev/urandom tr -dc A-Za-z0-9 | head -c${1:-32} | xclip -selection c"]
    lock:
      command: ["bash", "-c", "gnome-screensaver-command -l && xset dpms force off"]
    nautilus:
      command: ["nautilus", "--no-desktop"]
    minecraft yawkat:
      command: ["/home/yawkat/Development/Other/mcl/launcher.py", "yawkat"]
      jail:
      - "--whitelist=~/.minecraft"
      - "--whitelist=~/.config/mcl.json"
      - "--whitelist=~/Development/Other/mcl"
      - "--read-only=~/Development/Other/mcl"
    minecraft jonalu:
      command: ["/home/yawkat/Development/Other/mcl/launcher.py", "jonas.konrad@googlemail.com"]
      jail:
      - "--whitelist=~/.minecraft"
      - "--whitelist=~/.config/mcl.json"
      - "--whitelist=~/Development/Other/mcl"
      - "--read-only=~/Development/Other/mcl"
    windows:
      command: ["/home/yawkat/windows.sh"]
  shutdownCommand: ["systemctl", "poweroff"]
password: 
  cacheDir: "/home/yawkat/.local/share/password"
  timeout: 600
  remote: https://pw.yawk.at
  editorBackground: '#002b36'
  editorFont: base0
  editorWidth: 400
  editorHeight: 400
wallpaper: 
  cache: .cache/wallpaper
  input: wallpaper
  backgroundColor: '#002b36'
paste: 
  remote: https://s.yawk.at
