fontCacheDir: .cache/font/
fonts:
  base:
    background: '#002b36'
    foreground: '#93a1a1'
    italic: false
    bold: true
    size: 14
    family:
      name: "Ubuntu"
  foreground:
    parent: base
  foreground_highlight:
    parent: foreground
    foreground: '#fdf6e3'
  foreground_disabled:
    parent: foreground
    foreground: '#586e75'
  red:
    parent: foreground
    foreground: '#dc322f'
  green:
    parent: foreground
    foreground: '#859900'
  yellow:
    parent: foreground
    foreground: '#b58900'

  tac_base:
    parent: base
    background: '#002b36'
  tac_primary:
    parent: tac_base
    foreground: '#fdf6e3'
  tac_secondary:
    parent: tac_base
    foreground: '#586e75'
  tac_primary_selected:
    parent: foreground_highlight
    background: '#93a1a1'
  tac_secondary_selected:
    parent: foreground_disabled
    background: '#93a1a1'
dock:
  height: 20
  background: '#002b36'
  time: foreground
  batteryTime: foreground
  batteryTransition:
    low: red
    high: green
  cpuTransition:
    low: green
    high: red
  memoryTransition:
    low: green
    high: red
  swapTransition:
    low: green
    high: red
  clockFont: foreground
  clockFormat: "uuuu-MM-dd HH:mm:ss"
  netUpFont: yellow
  netDownFont: red
  activeFont: foreground_highlight
  runningFont: foreground
  emptyFont: foreground_disabled
  windowTitleFont: foreground
  progressColor: '#93a1a1'
tac:
  fontPrimary: tac_primary
  fontPrimarySelected: tac_primary_selected
  fontSecondary: tac_secondary
  fontSecondarySelected: tac_secondary_selected
  colorBackground: '#002b36'
  colorSelected: '#93a1a1'
  width: 400
  rowHeight: 20
shortcuts: 
  firefox:
    command: ["firefox"]
    jail: true
  thunderbird:
    command: ["thunderbird"]
    jail: true
  quasselclient:
    command: ["quasselclient"]
    jail: true
  subl:
    command: ["subl"]
  intellij:
    command: ["intellij-idea-ultimate-edition"]
  android-studio:
    command: ["android-studio"]
  genpw16:
    command: ["bash", "-c", "< /dev/urandom tr -dc A-Za-z0-9 | head -c${1:-16} | xclip -selection c"]
  genpw32:
    command: ["bash", "-c", "< /dev/urandom tr -dc A-Za-z0-9 | head -c${1:-32} | xclip -selection c"]
  lock:
    command: ["bash", "-c", "gnome-screensaver-command -l && xset dpms force off"]
  nautilus:
    command: ["nautilus", "--no-desktop"]
  minecraft yawkat:
    command: ["minecraft", "yawkat"]
  minecraft jonalu:
    command: ["minecraft", "jonas.konrad@googlemail.com"]
  steven yawkat:
    command: ["steven", "yawkat"]
  steven jonalu:
    command: ["steven", "jonas.konrad@googlemail.com"]
shutdownCommand: ["systemctl", "poweroff"]
password: 
  cacheDir: "/home/yawkat/.local/share/password"
  timeout: 600
  host: pw.yawk.at
  editorBackground: '#002b36'
  editorFont: foreground
  editorWidth: 400
  editorHeight: 400
wallpaper: 
  cache: .cache/wallpaper
  input: wallpaper
  backgroundColor: '#002b36'
paste: 
  remote: http://s.yawk.at
