style:
  fontCacheDir: .cache/font/
  fonts:
    base:
      background: '#002b36' # base03
      foreground: '#ffffff'
      italic: false
      bold: false
      size: 15
      family:
        name: "Source Code Pro"
    # Text Colors
    base03:
      parent: base
      foreground: '#002b36'
    base02:
      parent: base
      foreground: '#073642'
    base01:
      parent: base
      foreground: '#586e75'
    base00:
      parent: base
      foreground: '#657b83'
    base0:
      parent: base
      foreground: '#839496'
    base1:
      parent: base
      foreground: '#93a1a1'
    base2:
      parent: base
      foreground: '#eee8d5'
    base3:
      parent: base
      foreground: '#fdf6e3'

    highlight:
      parent: base2
      background: '#073642' # base02
    red:
      parent: base
      foreground: '#dc322f'
    green:
      parent: base
      foreground: '#859900'
    yellow:
      parent: base
      foreground: '#b58900'

    tac_primary:
      parent: base1
    tac_secondary:
      parent: base01
    tac_primary_selected:
      parent: tac_primary
      background: '#073642' # base02
    tac_secondary_selected:
      parent: tac_secondary
      background: '#073642' # base02

# Modules
dock:
  height: 20
  background: '#002b36'
  time: base0
  batteryTime: base0
  batteryTransition:
    low: red
    high: green
  cpuTransition:
    low: green
    high: red
  memoryTransition:
    low: green
    high: red
  swapTransition:
    low: green
    high: red
  clockFont: base0
  clockFormat: "uuuu-MM-dd HH:mm:ss"
  netUpFont: yellow
  netDownFont: red
  activeFont: highlight
  runningFont: base0
  emptyFont: base01
  windowTitleFont: base01
  progressColor: '#93a1a1'
tac:
  fontPrimary: tac_primary
  fontPrimarySelected: tac_primary_selected
  fontSecondary: tac_secondary
  fontSecondarySelected: tac_secondary_selected
  colorBackground: '#002b36'
  colorSelected: '#073642'
  width: 400
  rowHeight: 22
  padding: 3
launcher:
  shortcuts:
    firefox:
      command: ["firefox"]
      jail: true
    thunderbird:
      command: ["thunderbird"]
      jail: true
    quasselclient:
      command: ["quasselclient"]
      jail: true
    subl:
      command: ["subl"]
    intellij:
      command: ["intellij-idea-ultimate-edition"]
    android-studio:
      command: ["android-studio"]
    genpw16:
      command: ["bash", "-c", "< /dev/urandom tr -dc A-Za-z0-9 | head -c${1:-16} | xclip -selection c"]
    genpw32:
      command: ["bash", "-c", "< /dev/urandom tr -dc A-Za-z0-9 | head -c${1:-32} | xclip -selection c"]
    lock:
      command: ["bash", "-c", "gnome-screensaver-command -l && xset dpms force off"]
    nautilus:
      command: ["nautilus", "--no-desktop"]
    minecraft yawkat:
      command: ["minecraft", "yawkat"]
    minecraft jonalu:
      command: ["minecraft", "jonas.konrad@googlemail.com"]
    steven yawkat:
      command: ["steven", "yawkat"]
    steven jonalu:
      command: ["steven", "jonas.konrad@googlemail.com"]
  shutdownCommand: ["systemctl", "poweroff"]
password: 
  cacheDir: "/home/yawkat/.local/share/password"
  timeout: 600
  host: pw.yawk.at
  editorBackground: '#002b36'
  editorFont: base0
  editorWidth: 400
  editorHeight: 400
wallpaper: 
  cache: .cache/wallpaper
  input: wallpaper
  backgroundColor: '#002b36'
paste: 
  remote: http://s.yawk.at
