fontCacheDir: .cache/font/
dock: 
  height: 16
  background: '#002b36'
  time: 
    color: '#93a1a1'
  batteryTime: 
    color: '#93a1a1'
  batteryPercentageColorLow: '#dc322f'
  batteryPercentageColorHigh: '#859900'
  cpuColorHigh: '#dc322f'
  cpuColorLow: '#859900'
  memoryColorHigh: '#dc322f'
  memoryColorLow: '#859900'
  swapColorHigh: '#dc322f'
  swapColorLow: '#859900'
  clockFont: 
    color: '#93a1a1'
  clockFormat: "uuuu-MM-dd HH:mm:ss"
  netUpFont: 
    color: '#b58900'
  netDownFont: 
    color: '#dc322f'
  activeFont: 
    color: '#fdf6e3'
  runningFont: 
    color: '#93a1a1'
  emptyFont: 
    color: '#586e75'
  windowTitleFont: 
    color: '#93a1a1'
  progressColor: '#93a1a1'
font: 
  name: "Ubuntu"
tac: 
  fontNormal: 
    color: '#fdf6e3'
  fontLowPriority: 
    color: '#586e75'
  colorBackground: '#002b36'
  colorSelected: '#93a1a1'
  width: 400
shortcuts: 
  firefox:
    command: ["firefox"]
    jail: true
  thunderbird:
    command: ["thunderbird"]
    jail: true
  quasselclient:
    command: ["quasselclient"]
    jail: true
  subl:
    command: ["subl"]
  intellij:
    command: ["intellij-idea-ultimate-edition"]
  android-studio:
    command: ["android-studio"]
  genpw16:
    command: ["bash", "-c", "< /dev/urandom tr -dc A-Za-z0-9 | head -c${1:-16} | xclip -selection c"]
  genpw32:
    command: ["bash", "-c", "< /dev/urandom tr -dc A-Za-z0-9 | head -c${1:-32} | xclip -selection c"]
  lock:
    command: ["bash", "-c", "gnome-screensaver-command -l && xset dpms force off"]
  nautilus:
    command: ["nautilus", "--no-desktop"]
  minecraft yawkat:
    command: ["minecraft", "yawkat"]
  minecraft jonalu:
    command: ["minecraft", "jonas.konrad@googlemail.com"]
  steven yawkat:
    command: ["steven", "yawkat"]
  steven jonalu:
    command: ["steven", "jonas.konrad@googlemail.com"]
shutdownCommand: ["systemctl", "poweroff"]
password: 
  cacheDir: "/home/yawkat/.local/share/password"
  timeout: 600
  host: pw.yawk.at
  editorBackground: '#002b36'
  editorFont: 
    name: Ubuntu
  editorFontStyle:
    color: '#93a1a1'
  editorWidth: 400
  editorHeight: 400
wallpaper: 
  cache: .cache/wallpaper
  input: wallpaper
  backgroundColor: '#002b36'
paste: 
  remote: http://s.yawk.at
